-- Initial schema: the six supported games plus the mods table.
-- Schema versioning is handled by sqlx migrations; do not edit this file
-- after it has shipped — write a new migration instead.

CREATE TABLE IF NOT EXISTS games (
    code         TEXT PRIMARY KEY,
    install_path TEXT
);

INSERT INTO games (code) VALUES
    ('gimi'),
    ('srmi'),
    ('zzmi'),
    ('wwmi'),
    ('himi'),
    ('efmi');

CREATE TABLE IF NOT EXISTS mods (
    id                TEXT PRIMARY KEY,
    game_code         TEXT NOT NULL REFERENCES games(code),
    name              TEXT NOT NULL,
    source            TEXT NOT NULL,
    library_path      TEXT NOT NULL,
    junction_dir_name TEXT NOT NULL,
    enabled           INTEGER NOT NULL DEFAULT 0,
    created_at        TEXT NOT NULL,
    UNIQUE (game_code, junction_dir_name)
);

CREATE INDEX IF NOT EXISTS idx_mods_game_code ON mods(game_code);
