//! Structural ownership of durable Library witness SQL.

use std::fs;
use std::path::Path;

use gmm_lib::core::DURABLE_WITNESS_TABLES;

const OWNER: &str = "library_mutation.rs";

/// The table registry is generated by the same declaration that generates both
/// raw witness row shapes. Any production reference outside the owning module
/// therefore fails this named test instead of creating another unvalidated
/// SQLite-to-filesystem path.
#[test]
fn durable_witness_tables_are_only_queried_by_their_owning_module() {
    let core = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/core");
    let mut violations = Vec::new();
    let mut pending = vec![core.clone()];
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(&directory).expect("read core source directory") {
            let path = entry.expect("read core source entry").path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            if path.extension().and_then(|extension| extension.to_str()) != Some("rs")
                || path == core.join(OWNER)
            {
                continue;
            }
            let source = fs::read_to_string(&path).expect("read core source file");
            let executable_source = source
                .lines()
                .filter(|line| !line.trim_start().starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n");
            for table in DURABLE_WITNESS_TABLES {
                if executable_source.contains(table) {
                    violations.push(format!(
                        "{} references {table}",
                        path.strip_prefix(&core)
                            .expect("source below core")
                            .display()
                    ));
                }
            }
        }
    }
    assert!(
        violations.is_empty(),
        "durable witness SQL escaped {OWNER}; route every query through its validated loader: {violations:?}",
    );
}
