//! Structural ownership of durable Library witness SQL.

use std::fs;
use std::path::Path;

use gmm_lib::core::DURABLE_WITNESS_TABLES;
use proc_macro2::{TokenStream, TokenTree};
use syn::visit::{self, Visit};

const OWNER: &str = "core/library_mutation.rs";

/// The table registry is generated by the same declaration that generates both
/// raw witness row shapes. This test parses every production Rust file under
/// `src/` and inspects decoded string literals plus macro token trees. It catches
/// direct references, `const` and runtime concatenation of literal fragments,
/// helper-macro bodies, `stringify!` identifiers, and SQL loaded by the SQLx
/// `query_file!` family. It deliberately does not claim to prove SQL assembled
/// from runtime input, generated into `OUT_DIR`, or imported from a non-literal
/// path; those require review at the owning-module boundary.
#[test]
fn durable_witness_tables_are_only_queried_by_their_owning_module() {
    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let production = crate_root.join("src");
    let owner = production.join(OWNER);
    let mut violations = Vec::new();
    let mut pending = vec![production.clone()];
    while let Some(directory) = pending.pop() {
        for entry in fs::read_dir(&directory).expect("read production source directory") {
            let path = entry.expect("read production source entry").path();
            if path.is_dir() {
                pending.push(path);
                continue;
            }
            if path.extension().and_then(|extension| extension.to_str()) != Some("rs")
                || path == owner
            {
                continue;
            }
            let source = fs::read_to_string(&path).expect("read production Rust source file");
            let syntax = syn::parse_file(&source).unwrap_or_else(|error| {
                panic!("parse production Rust source {}: {error}", path.display())
            });
            let mut references = WitnessReferences::default();
            references.visit_file(&syntax);
            let stitched_literals = references.literal_fragments.concat();
            let stitched_identifiers = references.identifiers.concat();
            for table in DURABLE_WITNESS_TABLES {
                let literal_reference = references
                    .literal_fragments
                    .iter()
                    .any(|fragment| fragment.contains(table))
                    || stitched_literals.contains(table);
                let macro_identifier_reference = references
                    .identifiers
                    .iter()
                    .any(|identifier| identifier == table)
                    || stitched_identifiers.contains(table);
                let query_file_reference = references.query_files.iter().any(|query_file| {
                    let sql_path = crate_root.join(query_file);
                    let sql = fs::read_to_string(&sql_path).unwrap_or_else(|error| {
                        panic!(
                            "read SQLx query file {} referenced by {}: {error}",
                            sql_path.display(),
                            path.display(),
                        )
                    });
                    sql.contains(table)
                });
                if literal_reference || macro_identifier_reference || query_file_reference {
                    violations.push(format!(
                        "{} references {table}",
                        path.strip_prefix(&production)
                            .expect("source below production root")
                            .display()
                    ));
                }
            }
        }
    }
    assert!(
        violations.is_empty(),
        "durable witness SQL escaped {OWNER}; route every query through its validated loader: {violations:?}",
    );
}

#[derive(Default)]
struct WitnessReferences {
    literal_fragments: Vec<String>,
    identifiers: Vec<String>,
    query_files: Vec<String>,
}

impl<'ast> Visit<'ast> for WitnessReferences {
    fn visit_attribute(&mut self, attribute: &'ast syn::Attribute) {
        if attribute.path().is_ident("doc") {
            return;
        }
        visit::visit_attribute(self, attribute);
    }

    fn visit_lit_str(&mut self, literal: &'ast syn::LitStr) {
        self.literal_fragments.push(literal.value());
        visit::visit_lit_str(self, literal);
    }

    fn visit_macro(&mut self, invocation: &'ast syn::Macro) {
        let is_query_file = invocation
            .path
            .segments
            .last()
            .is_some_and(|segment| segment.ident.to_string().starts_with("query_file"));
        let first_literal = collect_macro_tokens(
            invocation.tokens.clone(),
            &mut self.literal_fragments,
            &mut self.identifiers,
        );
        if is_query_file {
            let Some(query_file) = first_literal else {
                panic!(
                    "SQLx {} must use a literal query-file path for witness-boundary inspection",
                    invocation
                        .path
                        .segments
                        .last()
                        .expect("macro segment")
                        .ident,
                );
            };
            self.query_files.push(query_file);
        }
        visit::visit_macro(self, invocation);
    }
}

fn collect_macro_tokens(
    tokens: TokenStream,
    literal_fragments: &mut Vec<String>,
    identifiers: &mut Vec<String>,
) -> Option<String> {
    let mut first_literal = None;
    for token in tokens {
        match token {
            TokenTree::Group(group) => {
                let nested = collect_macro_tokens(group.stream(), literal_fragments, identifiers);
                if first_literal.is_none() {
                    first_literal = nested;
                }
            }
            TokenTree::Ident(identifier) => identifiers.push(identifier.to_string()),
            TokenTree::Literal(literal) => {
                if let Ok(string) = syn::parse_str::<syn::LitStr>(&literal.to_string()) {
                    let value = string.value();
                    if first_literal.is_none() {
                        first_literal = Some(value.clone());
                    }
                    literal_fragments.push(value);
                }
            }
            TokenTree::Punct(_) => {}
        }
    }
    first_literal
}
